services:
  api1:
    build: ./api1
    ports:
      - "3001:8080"  # host:container
    networks:
      - kafka-estudo

  api2:
    build: ./api2
    ports:
      - "3002:8080"
    networks:
      - kafka-estudo

networks:
  kafka-estudo:
